package ru.monitoring.mobile

import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue

/**
 * Держатель изменяемого UI-состояния экрана [MonitoringApp].
 *
 * Раньше эти переменные объявлялись прямо в теле @Composable-функции как
 * локальные `var ... by rememberSaveable`. Их накопилось столько, что
 * скомпилированный метод содержал сотни локальных переменных/регистров, и
 * dex-верификатор ART отклонял класс целиком
 * (`VerifyError: invalid arg count (0) in range invoke`). Сбор состояния в
 * один объект-холдер кратно снижает число регистров метода и устраняет сбой.
 */
internal class MonitoringScreenState {
    var isManagementExpanded by mutableStateOf(false)
    var isSshAuthExpanded by mutableStateOf(false)
    var isWindowsAuthExpanded by mutableStateOf(false)
    var authWindowsTab by mutableStateOf("accounts")
    var windowsCredFilterType by mutableStateOf("")
    var isAddWindowsCredOpen by mutableStateOf(false)
    var isCreateWindowsTypeOpen by mutableStateOf(false)
    var isMergeWindowsTypesOpen by mutableStateOf(false)
    var windowsCredDeleteConfirmId by mutableStateOf(-1)
    var windowsTypeDeleteConfirmName by mutableStateOf("")
    var windowsTypeRenameSource by mutableStateOf("")
    var showServerAvailabilityDialog by mutableStateOf(false)
    var showServerAddDialog by mutableStateOf(false)
    var serverActionsTargetKey by mutableStateOf("")
    var serverDeleteConfirmTargetKey by mutableStateOf("")
    var serverCardsSortMode by mutableStateOf(ServerCardsSortMode.BY_NAME.name)
    var showServerResourcesMenu by mutableStateOf(false)
    var showServerResourcesDetailsDialog by mutableStateOf(false)
    var showTileHelpDialog by mutableStateOf(false)
    var tileHelpTitle by mutableStateOf("")
    var tileHelpDescription by mutableStateOf("")
    var serverResourceDetailsTargetKey by mutableStateOf("")
    var serverResourceDetailsTitle by mutableStateOf("")
    var areOpsTilesExpanded by mutableStateOf(false)
    var showTileSettingsDialog by mutableStateOf(false)
    var settingsSection by mutableStateOf("bff")
    var showSettingsSectionOverlay by mutableStateOf(false)
    var showProxmoxPatternAddDialog by mutableStateOf(false)
    var showProxmoxPatternEditDialog by mutableStateOf(false)
    var proxmoxPatternCategoryInput by mutableStateOf("proxmox")
    var proxmoxPatternTypeInput by mutableStateOf("subject")
    var proxmoxPatternValueInput by mutableStateOf("")
    var proxmoxPatternEditAction by mutableStateOf("")
    var patternDialogReturnAction by mutableStateOf("settings_patterns_proxmox")
    var proxmoxPatternEditTypeInput by mutableStateOf("subject")
    var proxmoxPatternEditValueInput by mutableStateOf("")
    var showMailPatternAddDialog by mutableStateOf(false)
    var showMailPatternEditDialog by mutableStateOf(false)
    var mailPatternInputMode by mutableStateOf("subject")
    var mailPatternInputValue by mutableStateOf("")
    var mailPatternEditAction by mutableStateOf("")
    var mailPatternEditValueInput by mutableStateOf("")
    var showMailPatternsDialog by mutableStateOf(false)
    var showMailPatternActionsDialog by mutableStateOf(false)
    var selectedMailPatternLabel by mutableStateOf("")
    var selectedMailPatternEditAction by mutableStateOf("")
    var selectedMailPatternDeleteAction by mutableStateOf("")
    var returnToMailPatternsDialog by mutableStateOf(false)
    var showDbCategoryAddDialog by mutableStateOf(false)
    var dbCategoryInput by mutableStateOf("")
    var showDbEntryAddDialog by mutableStateOf(false)
    var showDbOpsEntryAddDialog by mutableStateOf(false)
    var dbEntryAddCategory by mutableStateOf("")
    var dbEntryAddKeyInput by mutableStateOf("")
    var dbEntryAddNameInput by mutableStateOf("")
    var showDbEntryEditDialog by mutableStateOf(false)
    var dbEntryEditCategory by mutableStateOf("")
    var dbEntryEditOriginalKey by mutableStateOf("")
    var dbEntryEditNewKeyInput by mutableStateOf("")
    var dbEntryEditNameInput by mutableStateOf("")
    var showZfsHostAddDialog by mutableStateOf(false)
    var showZfsHostEditDialog by mutableStateOf(false)
    var showZfsStatusesDialog by mutableStateOf(false)
    var showZfsPoolFreeSpaceDialog by mutableStateOf(false)
    var showZfsPoolHostsSettingsDialog by mutableStateOf(false)
    var showZfsSettingsDialog by mutableStateOf(false)
    var showZfsHostsSettingsDialog by mutableStateOf(false)
    var showZfsHostActionsDialog by mutableStateOf(false)
    var showZfsPoolHostActionsDialog by mutableStateOf(false)
    var showZfsPoolHostAddDialog by mutableStateOf(false)
    var showZfsPoolHostEditDialog by mutableStateOf(false)
    var zfsPoolHostAddAction by mutableStateOf("zfsp_add")
    var pendingZfsPoolHostAddFromFreeSpaceDialog by mutableStateOf(false)
    var showZfsHostDetailsDialog by mutableStateOf(false)
    var showZfsPatternsDialog by mutableStateOf(false)
    var zfsHostInput by mutableStateOf("")
    var zfsHostEditAction by mutableStateOf("")
    var zfsHostEditCurrentName by mutableStateOf("")
    var zfsHostEditNewNameInput by mutableStateOf("")
    var zfsSelectedHostName by mutableStateOf("")
    var zfsSelectedHostEditAction by mutableStateOf("")
    var zfsSelectedHostDeleteAction by mutableStateOf("")
    var showZfsHostDeleteConfirmDialog by mutableStateOf(false)
    var zfsHostDeleteConfirmName by mutableStateOf("")
    var zfsHostDeleteConfirmAction by mutableStateOf("")
    var zfsSelectedHostToggleAction by mutableStateOf("")
    var zfsPoolSelectedHostName by mutableStateOf("")
    var zfsPoolSelectedHostEditNameAction by mutableStateOf("")
    var zfsPoolSelectedHostEditIpAction by mutableStateOf("")
    var zfsPoolSelectedHostEditThresholdAction by mutableStateOf("")
    var zfsPoolSelectedHostDeleteAction by mutableStateOf("")
    var zfsPoolSelectedHostToggleAction by mutableStateOf("")
    var zfsPoolHostNameInput by mutableStateOf("")
    var zfsPoolHostIpInput by mutableStateOf("")
    var zfsPoolHostThresholdInput by mutableStateOf("20")
    var zfsPoolHostEditNameInput by mutableStateOf("")
    var zfsPoolHostEditIpInput by mutableStateOf("")
    var zfsPoolHostEditThresholdInput by mutableStateOf("")
    var zfsDetailsHostName by mutableStateOf("")
    var zfsStatusDetailsFallbackText by mutableStateOf("")
    var pendingZfsHostSettingsName by mutableStateOf("")
    var showResourceThresholdDialog by mutableStateOf(false)
    var showResourceSettingsDialog by mutableStateOf(false)
    var resourceThresholdAction by mutableStateOf("")
    var resourceThresholdLabel by mutableStateOf("")
    var resourceThresholdValueInput by mutableStateOf("")
    var resourceThresholdCurrentValue by mutableStateOf<Int?>(null)
    var resourceThresholdOverrides by mutableStateOf<Map<String, Int>>(emptyMap())
    var selectedProxmoxBackupLabel by mutableStateOf("")
    var selectedDatabaseBackupLabel by mutableStateOf("")
    var showProxmoxBackupStatsDialog by mutableStateOf(false)
    var showProxmoxBackupsDialog by mutableStateOf(false)
    var showProxmoxPatternsDialog by mutableStateOf(false)
    var showProxmoxPatternActionsDialog by mutableStateOf(false)
    var selectedProxmoxPatternLabel by mutableStateOf("")
    var selectedProxmoxPatternEditAction by mutableStateOf("")
    var selectedProxmoxPatternDeleteAction by mutableStateOf("")
    var proxmoxPatternDeleteConfirmLabel by mutableStateOf("")
    var proxmoxPatternDeleteConfirmAction by mutableStateOf("")
    var showDatabaseBackupsDialog by mutableStateOf(false)
    var showMailBackupsDialog by mutableStateOf(false)
    var showDatabasePatternsDialog by mutableStateOf(false)
    var showDatabasePatternActionsDialog by mutableStateOf(false)
    var selectedDatabasePatternLabel by mutableStateOf("")
    var selectedDatabasePatternEditAction by mutableStateOf("")
    var selectedDatabasePatternDeleteAction by mutableStateOf("")
    var showProxmoxServerAddDialog by mutableStateOf(false)
    var proxmoxServerNameInput by mutableStateOf("")
    var proxmoxHostActionsTargetKey by mutableStateOf("")
    var proxmoxHostDeleteConfirmTargetKey by mutableStateOf("")
    var databaseActionsTargetAction by mutableStateOf("")
    var showStockLoadsDialog by mutableStateOf(false)
    var showSnapshotTransferDialog by mutableStateOf(false)
    var showMorningReportDialog by mutableStateOf(false)
}

@Composable
internal fun rememberMonitoringScreenState(): MonitoringScreenState =
    remember { MonitoringScreenState() }
