package ru.monitoring.mobile

import androidx.compose.runtime.Immutable
import ru.monitoring.mobile.api.ManagedServer

// Все колбэки экрана MonitoringApp собраны в один объект-холдер.
// Раньше они передавались ~94 отдельными параметрами @Composable-функции;
// при таком числе аргументов dex-верификатор ART отклонял класс целиком
// (java.lang.VerifyError: invalid arg count в invoke-*-range) и приложение
// падало на старте. Один параметр-холдер убирает ограничение с запасом.
@Immutable
class MonitoringAppCallbacks(
    val onTokenChanged: (String) -> Unit,
    val onBaseUrlChanged: (String) -> Unit,
    val onSaveToken: (String) -> Unit,
    val onSaveBaseUrl: () -> Unit,
    val onRefreshData: () -> Unit,
    val onCheckCertificateOnly: () -> Unit,
    val onLoadServersForSingleCheck: () -> Unit,
    val onLoadTileData: (String) -> Unit,
    val onEnsureSettingsLoaded: () -> Unit,
    val onRefresh: () -> Unit,
    val onCloseApp: () -> Unit,
    val onToggleApiTokenVisibility: () -> Unit,
    val onToggleTelegramTokenVisibility: () -> Unit,
    val onToggleExtension: (String, Boolean) -> Unit,
    val onEnableAllExtensions: () -> Unit,
    val onDisableAllExtensions: () -> Unit,
    val onOpenExtensionsSettingsMenu: () -> Unit,
    val onExtensionsSettingsAction: (String) -> Unit,
    val onAction: (String) -> Unit,
    val onCheckIntervalChanged: (String) -> Unit,
    val onTimeoutChanged: (String) -> Unit,
    val onMaxDowntimeChanged: (String) -> Unit,
    val onWindows2025TimeoutChanged: (String) -> Unit,
    val onDomainServersTimeoutChanged: (String) -> Unit,
    val onAdminServersTimeoutChanged: (String) -> Unit,
    val onStandardWindowsTimeoutChanged: (String) -> Unit,
    val onLinuxTimeoutChanged: (String) -> Unit,
    val onPingTimeoutChanged: (String) -> Unit,
    val onSaveMonitoring: () -> Unit,
    val onTelegramTokenChanged: (String) -> Unit,
    val onTelegramChatIdChanged: (String) -> Unit,
    val onSaveBot: () -> Unit,
    val onTestBotServerConnection: () -> Unit,
    val onTestBffConnection: () -> Unit,
    val onNewTelegramChatIdChanged: (String) -> Unit,
    val onAddTelegramChatId: () -> Unit,
    val onRemoveTelegramChatId: (String) -> Unit,
    val onMatrixHomeserverChanged: (String) -> Unit,
    val onMatrixAccessTokenChanged: (String) -> Unit,
    val onMatrixRoomIdChanged: (String) -> Unit,
    val onToggleMatrixAccessTokenVisibility: () -> Unit,
    val onSaveMatrixBot: () -> Unit,
    val onTestMatrixBotServerConnection: () -> Unit,
    val onQuietStartChanged: (String) -> Unit,
    val onQuietEndChanged: (String) -> Unit,
    val onMetricsTimeChanged: (String) -> Unit,
    val onSaveTime: () -> Unit,
    val onAuthModeChanged: (String) -> Unit,
    val onSshUsernameChanged: (String) -> Unit,
    val onSshKeyPathChanged: (String) -> Unit,
    val onSshPortChanged: (String) -> Unit,
    val onWindowsUsernameChanged: (String) -> Unit,
    val onSshPasswordChanged: (String) -> Unit,
    val onWindowsPasswordChanged: (String) -> Unit,
    val onToggleSshPasswordVisibility: () -> Unit,
    val onToggleWindowsPasswordVisibility: () -> Unit,
    val onSaveAuth: () -> Unit,
    val onWindowsCredUsernameChanged: (String) -> Unit,
    val onWindowsCredPasswordChanged: (String) -> Unit,
    val onWindowsCredServerTypeChanged: (String) -> Unit,
    val onWindowsCredPriorityChanged: (String) -> Unit,
    val onAddWindowsCredential: () -> Unit,
    val onRemoveWindowsCredential: (Int?) -> Unit,
    val onCreateWindowsTypeInputChanged: (String) -> Unit,
    val onRenameOldTypeInputChanged: (String) -> Unit,
    val onRenameNewTypeInputChanged: (String) -> Unit,
    val onMergeSourceTypeInputChanged: (String) -> Unit,
    val onMergeTargetTypeInputChanged: (String) -> Unit,
    val onDeleteTypeInputChanged: (String) -> Unit,
    val onDeleteTargetTypeInputChanged: (String) -> Unit,
    val onCreateWindowsType: () -> Unit,
    val onRenameWindowsType: () -> Unit,
    val onMergeWindowsTypes: () -> Unit,
    val onDeleteWindowsType: () -> Unit,
    val onServerIpChanged: (String) -> Unit,
    val onServerNameChanged: (String) -> Unit,
    val onServerTypeChanged: (String) -> Unit,
    val onServerTimeoutChanged: (String) -> Unit,
    val onSaveServer: () -> Unit,
    val onCheckServerAvailability: (ManagedServer) -> Unit,
    val onCheckServerResources: (ManagedServer) -> Unit,
    val onToggleProxmoxBackupMenu: () -> Unit,
    val onToggleDatabaseBackupMenu: () -> Unit,
    val onToggleMailBackupMenu: () -> Unit,
    val onEditServer: (ManagedServer) -> Unit,
    val onCancelServerEdit: () -> Unit,
    val onDeleteServer: (String) -> Unit,
    val onToggleServerMonitoring: (String, Boolean) -> Unit,
    val onThemeModeChanged: (String) -> Unit,
    val onMorningNotificationsEnabledChanged: (Boolean) -> Unit,
    val onMarkMorningReportRead: () -> Unit,
    val onFetchProxmoxHostBackups: (String) -> Unit,
    val onCloseProxmoxHostBackups: () -> Unit,
    val onOpenUpdateUrl: (String) -> Unit
)
